kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-probe-test
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-probe-test
  template:
    metadata:
      labels:
        app: k8s-probe-test
    spec:
      containers:
        - name: k8s-probe-test
          image: digitcontainerregistry.azurecr.io/k8s-probe-test:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          startupProbe:
            httpGet:
              path: /startupProbe
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: http
              scheme: HTTP
            initialDelaySeconds: 35
            timeoutSeconds: 1
            periodSeconds: 41
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: http
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 1
            periodSeconds: 42
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
